---
- name: Prompt action to perform
  hosts: all
  gather_facts: true
  vars_prompt:
    # Define what action to do here
    - name: "task_action"
      prompt: "Action"
      private: false

  tasks:
    - name: Display OS Family of each servers
      ansible.builtin.debug:
        msg:
          - "OS: {{ ansible_facts['os_family']}}"

    - name: Display server info
      ansible.builtin.include_tasks:
        "get-info/get{{ ansible_facts['os_family'] }}Info.yml"

    - name: "Route to OS-specific controller"
      ansible.builtin.include_tasks:
        "tasks/{{ ansible_facts['os_family'] | lower }}/main_{{ ansible_facts['os_family'] | lower }}.yml"
