- name: Display basic Debian Info
  ansible.builtin.debug:
    msg:
      - "Hostname: {{ ansible_facts['hostname'] }}"
      - "OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
      - "Architecture: {{ ansible_facts['architecture'] }}"
      - "CPU cores: {{ ansible_facts['processor_cores'] }}"
      - "Total memory (MB): {{ ansible_facts['memtotal_mb'] }}"
      - "Swap memory (MB): {{ ansible_facts['swaptotal_mb'] }}"
      - "Uptime: {{ ansible_facts['uptime_seconds'] }}"
