- name: Find directory
  ansible.builtin.file:
    path: '/home/{{ ansible_user }}/Desktop'
    state: directory
    mode: '0755'

- name: Create a file with inline content
  ansible.builtin.copy:
    content: |
      Hello User!
      This file was created by Ansible via SSH
      Managed by:  'test_user'
      Created on: {{ ansible_facts['date_time']['date'] }}
    dest: '/home/{{ ansible_facts["user_id"] }}/Desktop/ubuntuTest.txt'
    mode: '0644'
