# this is a .ini file
; [group_1]
# IP 1 ansible_user=username
# IP 2 ansible_user=username
# IP 3 ansible_user=username

; [group_2]
# IP 4 ansible_user=username
# IP 5 ansible_user=username
# IP 6 ansible_user=username

; [group_3]
# IP 7 ansible_user=username
# IP 8 ansible_user=username
# IP 9 ansible_user=username